# Generated by Django 2.1.7 on 2019-06-11 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faisApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='realtime_usgs_data',
            managers=[
            ],
        ),
    ]
