# Generated by Django 2.1.7 on 2019-06-20 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('faisApp', '0003_post_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_local',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
