# Generated by Django 2.1.7 on 2019-06-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faisApp', '0004_post_local_date_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='us_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(max_length=2)),
                ('state_name', models.CharField(max_length=100)),
            ],
        ),
    ]
