# Generated by Django 2.1.7 on 2019-07-17 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('faisApp', '0005_us_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='twitter_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweets', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_url', models.URLField()),
                ('image_url', models.URLField()),
                ('Sentiment', models.IntegerField()),
            ],
        ),
    ]
