# Generated by Django 2.1.7 on 2019-07-22 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('faisApp', '0006_twitter_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='historical_usgs_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('discharge', models.FloatField()),
                ('gage_height', models.FloatField()),
            ],
        ),
    ]
