# Generated by Django 2.1.7 on 2019-07-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faisApp', '0007_historical_usgs_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='flood_station_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_number', models.CharField(max_length=100)),
            ],
        ),
    ]
