# Generated by Django 2.1.7 on 2019-07-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faisApp', '0009_select_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical_usgs_data',
            name='discharge',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='historical_usgs_data',
            name='gage_height',
            field=models.FloatField(blank=True),
        ),
    ]
