# Generated by Django 2.2.4 on 2019-08-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faisApp', '0011_auto_20190801_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='flood_station_list',
            name='station_name',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
