# Generated by Django 2.2.4 on 2019-08-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faisApp', '0012_flood_station_list_station_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='tweet_streamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('geo', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
    ]
