# Generated by Django 2.2.5 on 2019-10-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faisApp', '0013_tweet_streamer'),
    ]

    operations = [
        migrations.CreateModel(
            name='peak_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_no', models.CharField(max_length=100)),
                ('peak_dt', models.CharField(max_length=100)),
                ('peak_va', models.CharField(max_length=100)),
                ('gage_ht', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='post_local',
            name='author',
        ),
    ]
