# Generated by Django 3.0.5 on 2020-09-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faisApp', '0015_auto_20191030_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtime_usgs_data',
            name='avg_ht',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
