# Generated by Django 3.0.5 on 2020-10-08 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faisApp', '0017_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='name',
            new_name='user_name',
        ),
    ]
