# Generated by Django 3.0.5 on 2020-10-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faisApp', '0018_auto_20201008_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='user_name',
        ),
        migrations.AddField(
            model_name='data',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='flood_depth',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='additional_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='latitude',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='longitude',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='time_stamp',
            field=models.TimeField(null=True),
        ),
    ]
